### ISSUE TITLE
Maximal Square (Square with Max area consisting of all 1's in a binary matrix) | Dynamic Programming

### ISSUE THREAD

**Issue by tejasbirsingh** [rjkalash/hacktoberfest2021#152]
Given an m x n binary matrix filled with 0's and 1's, find the largest square containing only 1's and return its area.
Input: matrix = [["1","0","1","0","0"],
["1","0","1","1","1"],
["1","1","1","1","1"],
["1","0","0","1","0"]]
Output: 4

Input: matrix = [["0","1"],
["1","0"]]
Output: 1

Please Assign this issue to me for adding Maximal Square Dynamic Programming Problem Code in C++.

Points I will take care of:-

- Proper indentation
- Clean and Comment Code
- Time Complexity explanation
- Explained Sample Example

**Comment by tejasbirsingh** [comment]
I have made a PR. Please review and merge with main branch if it satisfies the standard. Thanks

**Comment by Sourajita21** [comment]
I want to work on this sir. Can you please assign it to me?. Thanks for your time sir.
