### ISSUE TITLE
Longest Increasing Subsequence | Dynamic Programming

### ISSUE THREAD

**Issue by tejasbirsingh** [rjkalash/hacktoberfest2021#206]
I would like to contribute the clean and proper code for Longest Increasing Subsequence Problem in C++
Given an integer array nums, return the length of the longest strictly increasing subsequence.

A subsequence is a sequence that can be derived from an array by deleting some or no elements without changing the order of the remaining elements. For example, [3,6,2,7] is a subsequence of the array [0,3,1,6,2,2,7].
Input: nums = [10,9,2,5,3,7,101,18]
Output: 4
Explanation: The longest increasing subsequence is [2,3,7,101], therefore the length is 4.

Things I will take care of:-

- Proper commented code 
- Explanation for every step and logic
- Samples test cases explained

Please assign this to me. Thanks

**Comment by tanvideshmukh29** [comment]
Hi! I would love to work on this issue..

Given an integer array nums, return the length of the longest strictly increasing subsequence.
A subsequence is a sequence that can be derived from an array by deleting some or no elements without changing the order of the remaining elements. For example, [3,6,2,7] is a subsequence of the array [0,3,1,6,2,2,7].

https://leetcode.com/problems/longest-increasing-subsequence/

can you please assign it to me?
