### ISSUE TITLE
ordered list

### ISSUE THREAD

**Issue by starrohan999** [rjkalash/hacktoberfest2021#30]

**Comment by starrohan999** [comment]
please assign it to me.

**Comment by starrohan999** [comment]
@rjkalash

**Comment by sidson1** [comment]
<!DOCTYPE html>
<html>
<body>

<h1>The ol element</h1>

<ol>
  <li>Coffee</li>
  <li>Tea</li>
  <li>Milk</li>
</ol>

<ol start="5">
  <li>Coffee</li>
  <li>Tea</li>
  <li>Milk</li>
</ol>
 
</body>
</html>

**Comment by rjkalash** [comment]
Make a code of it in html n submit it 👍
