### ISSUE TITLE
Miscellaneous

### ISSUE THREAD

**Issue by rjkalash** [rjkalash/hacktoberfest2021#58]
Here sumbit your codes,🥳

**Comment by Harshgupta5901** [comment]
what can we submit here

**Comment by ayushsaxena119** [comment]
Please assign this issue to me.

**Comment by HelloGit2309** [comment]
Sir please assign this issue to me. I want to contribute competitive programming codes.

**Comment by Harshgupta5901** [comment]
@rjkalash pls check #128 i have added scroll animation

**Comment by rjkalash** [comment]
bro this repo has been declared excluded not to be counted in hacktoberfest anymore.
