### ISSUE TITLE
style

### ISSUE THREAD

**Issue by rjkalash** [rjkalash/hacktoberfest2021#6]

**Comment by abhishek213-alb** [comment]
@rjkalash  please assign me

**Comment by abhishek213-alb** [comment]
@rjkalash I want to contribute why are you closing

**Comment by rjkalash** [comment]
Reopened

**Comment by abhishek213-alb** [comment]
@rjkalash what kind of styling can i contribute

**Comment by rjkalash** [comment]
Anything you can contribute,  like show some style work in html file and submit it

**Comment by abhishek213-alb** [comment]
okay thanks

**Comment by Harshgupta5901** [comment]
i want to contribute to this pls assign this to me

**Comment by abhishek213-alb** [comment]
@Harshgupta5901 already assigned to me check other issues

**Comment by rjkalash** [comment]
@abhishek213-alb your files have some issue, try to submit a single file of html

**Comment by abhishek213-alb** [comment]
@rjkalash okay

**Comment by rjkalash** [comment]
And don't worry , one task can be assigned to 10 people , doesn't make a difference

**Comment by abhishek213-alb** [comment]
@rjkalash done please check

**Comment by Harshgupta5901** [comment]
#92 pls check this i have added a styled progress bar @rjkalash

**Comment by rjkalash** [comment]
All done bro
