### ISSUE TITLE
Excluded Project

### ISSUE THREAD

**Issue by Harshgupta5901** [rjkalash/hacktoberfest2021#616]
![image](https://user-images.githubusercontent.com/75782910/135756086-a234bc73-ebf9-4e86-bad6-3ff89370f8cb.png)

**Comment by Harshgupta5901** [comment]
@rjkalash 
why is it showing excluded?

**Comment by doniambarita** [comment]
Unfortunately, your pull request was made on a repository that doesn’t align with the core values of Hacktoberfest. For more information please read the Resources page. 
We’ve decided that pull requests made to this repository will not count toward completing the challenge.

Source : https://hacktoberfest.digitalocean.com/faq

**Comment by rjkalash** [comment]
My repo is canceled

**Comment by Harshgupta5901** [comment]
okk
