### ISSUE TITLE
Excluded Project

### ISSUE THREAD

**Issue by code08-ind** [rjkalash/hacktoberfest2021#631]
![Screenshot_2021-10-03-20-23-07-447_com android chrome](https://user-images.githubusercontent.com/69002338/135759450-21c5f147-d340-4023-be90-fcaf4407406f.jpg)

Your Project is Excluded. Help me out of this. My two PR in your repo are excluded.

**Comment by rjkalash** [comment]
Yup , send to some other repo

**Comment by code08-ind** [comment]
Closed
