### ISSUE TITLE
Program to check prime or not

### ISSUE THREAD

**Issue by ajithShine5** [rjkalash/hacktoberfest2021#702]

**Comment by GoutamVerma** [comment]
hey @ajithShine5  can you please assign this issue to me?

**Comment by GoutamVerma** [comment]
Can I use C++ for this issue

**Comment by karankc23** [comment]
@rjkalash please assign this issue to me in c++ or  c

**Comment by arjunpundir1106** [comment]
@rjkalash can i work on this issue in java?

**Comment by ajithShine5** [comment]
closing issus
